spring.application.name=routefinder

spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:31885/railway
spring.datasource.username=root
spring.datasource.password=bTNjXYSYeanMuPhcykKQKyVievQtYIxn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=${PORT:8081}
