spring.datasource.url=jdbc:mysql://localhost:3306/routeiq
spring.datasource.username=root
spring.datasource.password=Sipra_Singh@14

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
